media:
  input: src/images
  output: media
content:
  - name: blog
    label: Articles
    path: src/content/blog
    type: collection
    fields:
      - name: title
      - name: description
      - name: pubDate
        type: date
        label: date
        options:
          format: yyyy-MM-dd