media:
  input: src/images
  output: media
content:
  - name: blog
    label: Articles
    path: src/content/blog
    type: collection
    view:
      fields: [ title, published, pubDate ]
    fields:
      - name: title
      - name: description
      - name: pubDate
        type: date
        label: date
        options:
          format: yyyy-MM-dd
      - name: featured
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text