media:
  input: src/images
  output: ../../images
content:
  - name: blog
    label: Articles
    path: src/content/blog
    filename: '{year}-{month}-{day}-{fields.title}.md'
    type: collection
    view:
      fields: [ title, published, featured, pubDate ]
    fields:
      - name: title
        type: string
        label: Title
      - name: description
        type: text
        label: Description
      - name: pubDate
        type: date
        label: Published Date
        options:
          format: yyyy-MM-dd
      - name: updatedDate
        type: date
        label: Updated Date
        options:
          format: yyyy-MM-dd
      - name: heroImage
        type: image
        label: Hero Image
      - name: featured
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text